name: CI

on: [push]

jobs:
  build:
    name: Build

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3.0.0
        
    - name: Get cache
      uses: actions/cache@v3.0.0
      id: cache
      with:
        path: |
          Pods
          PopcornTime.xcworkspace
          Podfile.lock
        key: ${{ hashFiles('Podfile.lock') }}

    - name: Get dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        sudo gem install cocoapods
        pod repo update
        pod update
                
    - name: Compile
      run: |
        sudo xcode-select -s /Applications/Xcode_13.0.app
        xcodebuild archive \
          -workspace PopcornTime.xcworkspace \
          -scheme TopShelf \
          -destination generic/platform=tvOS \
          -configuration Debug \
          CODE_SIGN_IDENTITY='' \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
        
    - name: Package
      run: |
        sudo find / -type d -name "PopcornTime (tvOS).app"
        cd ~
        mkdir Payload
        cp -r "Library/Developer/Xcode/DerivedData/*/Build/Intermediates.noindex/ArchiveIntermediates/*/InstallationBuildProductsLocation/Applications/PopcornTime (tvOS).app" Payload
        wget https://github.com/sbingner/ldid/releases/download/v2.1.4/osx-ldid.tgz
        tar -xvf osx-ldid.tgz
        ./ldid -S Payload/PopcornTime.app/PopcornTime
        zip -r popcorn_time.ipa Payload
        rm -r Payload
        
    - name: Upload
      uses: actions/upload-artifact@v3.0.0
      with:
        name: 'popcorn_time'
        path: |
          ~/popcorn_time.ipa
